### ISSUE TITLE
[Feature]: Add custom messenger bags for Maid and Tiger

### ISSUE THREAD

**Issue by Fluxom-Art** [WitchFreya/SWSAddons#161]
### Discord Handle

Tiger

### What type of config do you need?

Vehicle/UAV/Unit or similar (CfgVehicles)

### What's the base class or path?

n/a

### What texture are you trying to change?

n/a

### Describe the nature of the changes you want to make and any other details.

I want to add a medical bag for Tiger (see: same stats as medical satchel) using the messenger bag model, and add a Long Range Radio messenger bag for Maid
![b_messenger_maidLR_f_co](https://github.com/WitchFreya/SWSAddons/assets/156493483/a13eee26-7fb7-4b55-9564-244b25c1118d)
![b_messenger_tigerMedic_f_co](https://github.com/WitchFreya/SWSAddons/assets/156493483/ee34536e-559c-40b1-b868-e5083b5f5b80)

**Comment by WitchFreya** [comment]
Okay, I've got it in a branch! https://github.com/WitchFreya/SWSAddons/tree/161-design-add-configs-for-custom-messenger-bags

I also sent you another invite to act as a collaborator for the repo; the next steps are to pull this branch and then toss your files in to replace the placeholders. You can see an example of how it works in issue #146 and pull request #147; instructions for how to pull stuff are on the Wiki under [Texture Modifications: Sharing Your Changes](https://github.com/WitchFreya/SWSAddons/wiki/Part-2:-Texture-Modification-for-Designers#sharing-your-changes) and [Pull Requests for Designers](https://github.com/WitchFreya/SWSAddons/wiki/Part-3:-Pull-Requests-for-Designers), let me know if you want some help since it's your first time doing this!! 🎉
