### ISSUE TITLE
[Feature]: Increased turret health for base Arma turrets

### ISSUE THREAD

**Issue by Trigonshee** [WitchFreya/SWSAddons#260]
### Discord Handle

Trigonshee

### Describe what sort of feature you are looking to have added

Current turret health makes running certain turrets a risk based on low survivability. 
Class names: 
B_GMG_01_F
B_GMG_01_high_F
B_HMG_01_F
B_HMG_01_high_F
B_static_AT_F
B_static_AA_F
B_Mortar_01_F

I think the Mortar and the mini-spike AA (last two in list) might not need it, and I don't have a good use case for the mini-spike AA in a CSW team right now anyway.

**Comment by EidolonForgery** [comment]
## Base Classes for modification:
- **GMG_01_base_F:**
`base/Turrets/MainTurret/HitPoints/HitGun` & `/HitTurret` with a default value of `armor=0.3000001`
- **`GMG_01_high_base_F`** inherits from `GMG_01_base_F`, no additional change needed


- **`HMG_01_base_F`** inherits hitpoints from `StaticWeapon` by way of `StaticMGWeapon`: I'm uncomfortable with modifying a root class's armor so I'm going to modify the base directly, I think. Base config in `base/Turrets/MainTurret/HitPoints/HitGun` and `/HitTurret`, just like the GMG, with a default value of `armor=0.30000001;`.

- **`HMG_01_high_base_F`** inherits from `HMG_01_base_F`, no additional change needed

- **`AT_01_base_F`** ALSO inherits hitpoints from `StaticWeapon` via `StaticMGWeapon`. Identical change to above.

- **`B_Mortar_01_F`** ALSO ALSO inherits hitpoints from StaticWeapon, via StaticMortar.

**So,** either change `GMG_01_base_F` and `StaticWeapon` or change the armor values for `AT_01_base_F`, `AT_01_base_F`, and `B_Mortar_01_F` manually.  Which do we want to do? @WitchFreya 

Will gather comparative armor designations from mods to see how much more or less fragile they are.

**Comment by EidolonForgery** [comment]
Additional targets for revamp identified:

`HMG_02_base_F` and `HMG_02_high_base_F` are the turrets used by CLA and the like, the nice 50s with the shields. Some disappointments:
- The armor value of the shield is locked in the model so I can't change it
- This, too, inherits from `StaticWeapon`
However, it also confirms that we should also be bumping the global HP value of these turrets.

The 50 cal's base armor is 30. Remembering that "armor" is HP here, basically, it's no wonder that basic HMG fire tends to break these turrets. They also have `ExplosionShielding` of 4 and a `minTotalDamageThreshold` of 0.5.

I'll start toying with amounts. Our basic damage formula is `BulletHitDamage/Armor`, but the total "health" of the part is the local armor value (0.3) multiplied by the base armor (30) and globally by `ArmorStructural` (1, in this case, for no effect). Most of my complaints regarding turrets getting shredded is by gunfire rather than direct explosive hits, so maybe we'll tune up the threshold and HP while leaving the explosion shielding alone.

**Comment by WitchFreya** [comment]
Toy around with it, I'm not picky on where the change happens atm.

**Comment by EidolonForgery** [comment]
Update on this: Patching the base HP + structural armor seems like the way to go. We can make them very effective, even to the point of requiring a direct AT impact if desired.
